import Header from '@/app/components/Header'
import Footer from '@/app/components/Footer'
import './globals.css'
import { Sora } from 'next/font/google'

const sora = Sora({ subsets: ["latin"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='overflow-x-hidden'>
      <body className={`${sora.className} overflow-x-hidden`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
